sudo: required
services:
  -docker

env:
  COMPOSE_VERSION: 1.20.0-rc1

language: python
python:
  - "2.7"


    
before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin
   
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest tests/
  - docker-compose build
  - docker login --email=_ --username=_ --password=${HEROKU_AUTH_TOKEN} registry.heroku.com



